### ISSUE TITLE
Translation status should be "up to date" after automatic translation via SUMM.AI

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1724] opened 2022-09-30 07:35 UTC
After using the MT-Bulk-Action or SUMM.Ai the translation status should be updated otherwise one is not able to see which pages have already been translated.

Possibly we introduce a new translation status for "Machine Translation"? Or we use the checkmark but in a different color (orange = warning?)

~Edit: Decision; An orange checkmark is displayed for automatic, not reviewed translations. Translations without human-check should be online.~ see #1883

**Comment by osmers** [comment] 2022-12-01 11:50
Just to clarify the latest decision on this issue - we want to separate translation status from publication status. For SUMM AI translations we decided to have the robot translation icon (till they are checked and corrected, then green check mark) for the translation status and the publication status as "in review" (so not visible in the app, till checked and corrected, then published)

**Comment by timoludwig** [comment] 2022-12-01 13:50
@osmers ok, thanks for the clarification.

I'm now closing this ticket as duplicate because:

- The "up-to-date even when in review"-part is a duplicate of #1889
- The "new status for machine translation"-part is a duplicate of #1883

**Closed by timoludwig** 2022-12-01 13:50 UTC
Labels: good first issue, question, prio: high, enhancement, ui-ux, effort: low
