### ISSUE TITLE
Implement Glossary for DeepL in CMS

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#3045] opened 2024-09-13 14:45 UTC
### Motivation
Christine added a Glossary for DeepL and the API call needs to be changed to call the glossary as well.

### User Story
As a CMS user I want certain words to always be translated the same way so that there is no confusion for non-native speakers.

### Additional Context

https://chat.tuerantuer.org/digitalfabrik/pl/p36gwikmgjrbfe3x6asj5ge11r

**Comment by timobrembeck** [comment] 2024-09-14 10:05
Is this a duplicate of #1346?

**Comment by david-venhoff** [comment] 2024-09-14 10:31
> Is this a duplicate of https://github.com/digitalfabrik/integreat-cms/issues/1346?

This issue is only about modifying our api calls to deepl to tell it to use the already existing glossary.
The linked issue is about implementing a glossary managed by the cms. I have edited it to make this more clear now

**Comment by ChristineBruckner** [comment] 2024-09-14 10:36
DeepL Glossaries created from Integreat memoQ glossary
&amp; uploaded to DeepL API - May 2024, Christine
Bruckner


Glossary language combination | Glossary ID
DE-EN_2 | dba493bc-b18e-4173-ae04-664dfe1de0c9
DE-ES_2 | 588708de-eb3e-4f79-b8b5-bc8dbe19f346
DE-FR_2 | d0de3b7a-5986-4613-af00-3a42b476a6c2
DE-IT_2 | 303036a5-78e7-4550-b8eb-0bc7db446f82
DE-PL_2 | f14b3b4a-e9bb-4325-b1ca-613466e056e1
DE-RU_2 | 44930f57-f01b-4c15-a88e-8adf45cab5be

**Closed** 2024-11-15 16:37 UTC
Labels: feature, effort: low
