### ISSUE TITLE
Link checker recognizes a link to Google Map as internal link

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2465] opened 2023-10-16 10:29 UTC
### Describe the Bug

It seems link checker sometimes recognises a link to Google Map as internal link.

### Steps to Reproduce

1. Go to https://admin.integreat-app.de/lk-emmendingen/analytics/linkcheck/invalid/?page=2
2. Find a link with linktext "Hauptstraße 15, 79341 Kenzingen"
3. See "https://integreat.app/Hauptstra%C3%9Fe" in the URL column
4. Go to the source page
5. Find "https://www.google.com/maps/place/Hauptstra%C3%9Fe+15,+79341+Kenzingen/@48.1918235,7.7665451,17z/data=!3m1!4b1!4m6!3m5!1s0x47913cec05b5a17f:0xe65c8600197c8b17!8m2!3d48.19182!4d7.76912!16s%2Fg%2F11c5fw72pv?entry=ttu" in the link in the editor.

### Expected Behavior

The link to Google Map should be recognised as an external link.

### Actual Behavior

The link to Google Map is somehow recognised as an internal link.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by timobrembeck** [comment] 2023-10-16 10:37
@MizukiTemma Thanks a lot for creating the issue! I'm sorry, but apparently this was a false alarm, I checked all existing translations of this page, and older versions really contain this link:
```
In [10]: Page.objects.get(id=14442).translations.filter(content__icontains="https://integreat.app/Hauptstra").first().content
Out[10]: '... <a href="https://integreat.app/Hauptstra%C3%9Fe">Hauptstra&#223;e 15, 79341 Kenzingen</a> ...'
```
So it was not the CMS that's at fault for not recognizing the Google maps link here.
The problem is more that links of old versions are shown in the link checker - which is a result from an inconsistent database.
Unfortunately, we can't really prevent this at the moment, since the link checker library itself is not race condition safe (see https://github.com/DjangoAdminHackers/django-linkcheck/issues/168).
For the moment, I'm going to close this and create an infrastructure task to rescan the link db.

**Closed by timobrembeck** 2023-10-16 10:37 UTC
Labels: bug
