### ISSUE TITLE
Some broken links aren't identified

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1572] opened 2022-06-23 13:52 UTC
### Describe the Bug

Our system seems to miss some links that are apparently broken. So far I only identified links directing to integreat-app.de adresses, but as they return a 404 they should still be visible in our list.

### Expected Behavior

This links should be listed in our cms.

**Comment by david-venhoff** [comment] 2022-06-29 09:11
The links on https://integreat.app/marburg-biedenkopf/de/freizeit/vereine seem to be fixed now

**Comment by ulliholtgrave** [comment] 2022-06-29 10:59
Yes. They fixed them on the live system, but they found them by accident as they were not appearing in the broken links. I guess we have some cases where our library isn't triggered correctly. Normally it should scan our content when we are saving some related object. Either our library is kinda blind for some links (maybe related to https://github.com/digitalfabrik/integreat-cms/pull/1385 ?) or we have a case where the content is changed but it doesn't trigger the save (maybe during autosaves?). This are just some guesses that could be investigated...

However, If they encounter new missing links I'll update the issue.

**Comment by timoludwig** [comment] 2022-11-13 23:23
Since the region `marburg-biedenkopf` was created (probably cloned) on May 22, 2022 and this problem was reported on Jun 23, 2022, I'm pretty sure this is essentially a duplicate of #1513.

Also, we don't have any other reports since then with the same problem, do we? (Otherwise we would have updated the issue description because we need more info to be able to trace back this problem...)

**Closed** 2022-11-14 09:14 UTC
Labels: duplicate

**Comment by svenseeberg** [comment] 2022-11-14 09:15
This could also be related to (or be a duplicate of) #1818.
