### ISSUE TITLE
Media library empty after cloning

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1415] opened 2022-05-11 07:54 UTC
### Describe the Bug
When cloning a region the media library is empty.

### Steps to Reproduce

1. Create a region, then upload an image into the media library
2. Create another region and with the first region as template
3. Look into the media library, it is empty

### Expected Behavior
Media library items should be cloned.

### Actual Behavior
Media library items are not cloned.

**Comment by timoludwig** [comment] 2022-05-11 07:59
Duplicate of #1414

**Closed by timoludwig** 2022-05-11 07:59 UTC
Labels: bug, prio: high

**Comment by svenseeberg** [comment] 2022-05-11 08:01
I just noticed :see_no_evil: thanks
