### ISSUE TITLE
Set logo for instance opens empty media library

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1584] opened 2022-07-04 08:36 UTC
If one tries to set a (PDF-print)-logo in the admin interface it opens a blank media library window and setting the logo is not possible

![Unbenannt](https://user-images.githubusercontent.com/4182469/177116215-8caa2c0a-113b-42fc-97e9-d75797f33474.PNG)

**Comment by timoludwig** [comment] 2022-07-04 08:38
Duplicate of #1578

**Closed** 2022-07-04 08:38 UTC
Labels: bug
