### ISSUE TITLE
Broken Link Checker stops when facing URL longer than 255 chars

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1818] opened 2022-11-01 11:36 UTC
### Describe the Bug
It seems that the broken link check LIFO queue is not being checked to the end if an error occurs. That means that if many links are checked at once (queue is being filled with many links) and one error occurs, many links are not being checked. The queue seems to live in memory and not in the database.

### Steps to Reproduce

1. I replaced links with the shell as described in https://issues.tuerantuer.org/browse/INFRA-217
2. After all links have been replaced, the link checker returns some warnings which indicate it is running
3. After some time, an error occurs and no further warnings appear. This indicates that the link validation process has stopped

### Expected Behavior
Errors should either be catched and the LIFO queue should normally be finished. Alternatively, the queue could be persisted, for example in the database, and continued with the next cron job.

### Actual Behavior
One error stops the link check process.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
[...]
/opt/integreat-cms/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'integreat.app'. Adding certificate verification is str
ongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/integreat-cms/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'integreat.app'. Adding certificate verification is str
ongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
linkcheck.models.DoesNotExist: Url matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/listeners.py", line 24, in linkcheck_worker
    task['target'](*task['args'], **task['kwargs'])
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/listeners.py", line 80, in do_check_instance_links
    u, created = Url.objects.get_or_create(url=url)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method       
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql           
    cursor.execute(sql, params)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/transaction.py", line 98, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(255)

In [2]:
  ```

</details>

**Comment by timoludwig** [comment] 2022-11-01 12:00
Not only the queue highlights a potential problem, but also the error message itself:
`linkcheck.models.DoesNotExist: Url matching query does not exist.`
It seems that there exist `Link` objects without a corresponding `URL` to check?

This seems to be a problem of the library and not the way we use it, right? Should we open an upstream issue in https://github.com/DjangoAdminHackers/django-linkcheck for this?

**Comment by timoludwig** [comment] 2022-11-13 23:56
I think this might be the real root cause of our problems.

Initially I thought this problem occurred during link _checking_ (which would make it less severe since unchecked links are not really relevant), but the traceback shows that this happened during the link _finding_ (since only then the `Url` objects are being created).

I could reproduce this behavior locally:

1. Reset the database with [./dev-tools/prune_database.sh](https://github.com/digitalfabrik/integreat-cms/blob/develop/dev-tools/prune_database.sh)
2. I create a long link (more than 255 characters): `python -c "print('http://httpstat.us/200?' + 300 * 'A')"`
3. I insert this link into a page and press "save"
4. The same error occurs as in the original traceback (`django.db.utils.DataError: value too long for type character varying(255)`)
5. Insert a normal, short link into another page and press "save"
6. Have a look in the link checker list - for me, also the short link was missing.

This problem persisted during the complete run time of the server, so the linkcheck process was completely dead until I restarted the server.

In theory, this problem was fixed in the upstream library by truncating the URL if it's too long: https://github.com/DjangoAdminHackers/django-linkcheck/issues/75

So we have to check whether this bug re-appeared in the library (and needs to be fixed there), or whether something in our custom setup causes this problem just for us.

A quick workaround would be to increase our max url length by setting `LINKCHECK_MAX_URL_LENGTH` to a higher value, but we should definitely find a more permanent solution...

**Comment by svenseeberg** [comment] 2022-11-15 14:54
I think that we should by default support longer URLs than 255 characters. Probably most websites do support shorter URLs, but many of them also have a lot of status information encoded in GET parameters or even the path. I think the supported length should be between 512 and 1024 characters.

The question is what we do with longer URLs? Maybe we should mark them as broken by default with a "too long" message?

**Comment by timoludwig** [comment] 2022-11-15 18:59
> I think that we should by default support longer URLs than 255 characters. Many users simply copy the address bar, which quite often is very long. Probably most websites do support shorter URLs, but many of them also have a lot of status information encoded in GET parameters or even the path. I think the supported length should be between 512 and 1024 characters.

Yes, I agree :+1:

> The question is what we do with longer URLs? Maybe we should mark them as broken by default with a "too long" message?

In theory, these links should already be skipped by the library:

https://github.com/DjangoAdminHackers/django-linkcheck/blob/d086a1ef2d8db56c6fe3f4e49f80238b9bcce782/linkcheck/utils.py#L120-L122

So not sure why we ran into this problem, needs further research I guess. I would not truncate the URLs without understanding why they're there in the first place.

**Comment by svenseeberg** [comment] 2022-11-15 19:01
> > The question is what we do with longer URLs? Maybe we should mark them as broken by default with a "too long" message?
> 
> In theory, these links should already be skipped by the library:

I think my question was more about the front end / user aspect. What do we tell the user? The URL has not been checked? I'd say we should indicate that there is something fundamentally wrong with the link.

**Comment by timoludwig** [comment] 2022-11-15 19:13
> I think my question was more about the front end / user aspect. What do we tell the user? The URL has not been checked? I'd say we should indicate that there is something "fundamentally wrong" with the link.

In theory, we shouldn't be able to tell the user anything, because the URL and corresponding link object should not exist according to the library's logic. I just don't understand why the CMS tried to create them nevertheless... 

If we want the URLs to show up, this would probably be more effort than appropriate, because we would either have to provide a contribution to the upstream repo with this feature or implement our own regex parser for finding these longer urls in the content etc... and if we increase the character limit, hopefully there aren't too many long URLs left. So if we just find the cause why the URLs were created in this case and can prevent this, I'm fine with the "silent" solution of just not showing these links in the checker at all...

**Comment by timoludwig** [comment] 2022-11-15 19:18
Ahh okay, I think I got it: The function `update_urls()` which correctly checks the URL's length is only called when the global scan is executed.
When the scan is triggered by the listener of the save signal however, the [do_check_instance_links()](https://github.com/DjangoAdminHackers/django-linkcheck/blob/d086a1ef2d8db56c6fe3f4e49f80238b9bcce782/linkcheck/listeners.py#L50) function is executed which does not correctly check the length of the URL...

So to me, it seems like a bug in the library which we could fix, but I'm not sure why there is no open ticket? Was this (kinda obvious) bug missed all these years?

**Comment by svenseeberg** [comment] 2022-11-15 19:21
> So to me, it seems like a bug in the library which we could fix, but I'm not sure why there is no open ticket? Was this (kinda obvious) bug missed all these years?

Sounds possible to me. We have a special user group.

**Comment by svenseeberg** [comment] 2022-11-18 12:00
The upstream PR to fix this problem: https://github.com/DjangoAdminHackers/django-linkcheck/pull/119

**Closed** 2023-01-10 11:38 UTC
Labels: bug
