### ISSUE TITLE
Escalation Button for the municipalities to send in technical feedback to Integreat Staff

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1458] opened 2022-05-21 09:47 UTC
### Motivation

Right now, the user can send the municipalities feedback on everything. This also includes the ability to give feedback to technical difficulties.
The App however does not sort out the sort of Feedback. 

### Proposed Solution

An escalation button in the backend, where the municipalities can divert the technical feedback to the Integreat staff.

**Comment by timoludwig** [comment] 2022-05-21 13:22
Duplicate of #757

**Closed by timoludwig** 2022-05-21 13:22 UTC
Labels: feature
