### ISSUE TITLE
Minor edit in default translations results in strange behavior for dependent translations

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1645] opened 2022-08-22 14:09 UTC
### Describe the Bug

If the default translation is only existing as a "minor edit" version uploading  translations results in them being directly out of date. We should also consider to forbid that the initial translation can be a minor edit as we have no other translations that might be impacted.

### Additional Information

See outdated status after upload.
![grafik](https://user-images.githubusercontent.com/15608678/185941111-ce6f71a3-1c4c-424e-b1ff-99de887d9c3f.png)

**Comment by timoludwig** [comment] 2022-08-22 15:31
I think we already prevent that the initial translation is minor when it's published - I agree that we should extend that so the initial translation cannot be minor independent of the status.

**Comment by timoludwig** [comment] 2022-08-22 15:35
Other than that, I think the current behavior is kind of expected: when the initial translation is a minor edit, it's only relevant for the default language and there should not be any translated content. "outdated" also means "something is wrong" and clearly something is wrong in this case... Where did the imported translations originate from? This workflow doesn't make sense.

**Comment by ulliholtgrave** [comment] 2022-08-22 16:32
I agree with your points. In this case we only have versions that are either minor edits or drafts in german. I guess that in this case the xliffs got created from drafts and then some other translations got published but the German version never got published.

**Comment by timoludwig** [comment] 2022-08-23 06:44
I just checked and in this particular case, the problem is a duplicate of #1464.
The page is published, but the latest public version is a minor edit and all previous versions are not public.
We made sure that the problem can no longer arise, but we did not fix it where it was existent in the database.
I suggest to convert this ticket into a Jira ticket, or do you think there is actually something we should change in the code base?

**Comment by ulliholtgrave** [comment] 2022-08-23 06:53
Okay, I agree. Let's convert it to a Jira task :+1:

**Closed** 2022-08-23 06:53 UTC
Labels: bug, prio: medium, effort: medium
