### ISSUE TITLE
All tests are failing with the same error

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1803] opened 2022-10-26 07:50 UTC
### Describe the Bug
When creating a PR, all tests will fail with the following error:

```
AttributeError: 'FileNotFoundError' object has no attribute 'winerror'

Exited with code exit status 1
```

### Steps to Reproduce

1. Create a PR with any branch and wait for the tests.

### Expected Behavior
Tests should work if no problem exists.

### Actual Behavior
All tests fail.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/core.py", line 2680, in _launch_windows_subprocess
    return subprocess.Popen([command] + script.args, **options)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/circleci/project/.venv/bin/black'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.9.15/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/cli/command.py", line 421, in run
    do_run(
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/core.py", line 2780, in do_run
    run_fn(*run_args, **run_kwargs)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/core.py", line 2690, in do_run_nt
    p = _launch_windows_subprocess(script, env)
  File "/home/circleci/.pyenv/versions/3.9.15/lib/python3.9/site-packages/pipenv/core.py", line 2682, in _launch_windows_subprocess
    if e.winerror != 193:
AttributeError: 'FileNotFoundError' object has no attribute 'winerror'
  ```

</details>

**Comment by timoludwig** [comment] 2022-10-26 07:51
This is a duplicate of #1732, see this issue and my corresponding PR #1798 for context information.

**Closed by timoludwig** 2022-10-26 07:51 UTC
Labels: bug, prio: urgent
