### ISSUE TITLE
Sorting pages has effect on multiple pages (instead of only 1 page)

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1644] opened 2022-08-22 12:21 UTC
### Describe the Bug
I try to sort the page "Information..." on position 1 and "Weitere Schritte..." has to be on the last position of the chapter. If I move one of them, both move (see Video).

https://user-images.githubusercontent.com/4182469/185919763-e06b27e6-17fa-4bb5-af0f-0eeda9438f6c.mp4

**Comment by timoludwig** [comment] 2022-08-24 11:16
I could not reproduce this problem locally, so this does not seem to be a sorting bug.
Apparently the internal tree structure was broken (the two pages which kept being moved together had the same `lft` and `rgt` values in the mptt model), I have now fixed it manually in the database.
It's hard to tell where this problem originated from, one possible culprit could be a race condition: #1518

**Closed by timoludwig** 2022-08-24 11:16 UTC
Labels: bug
