### ISSUE TITLE
Wrong validation of PushNotification forms

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1641] opened 2022-08-17 16:25 UTC
### Describe the Bug

Our service team reported that push notifications are getting sent even if the form validation fails. In this specific case the message was too long and the message couldn't be sent. However, our system sent the notification via firebase and the apps couldn't receive the full message from our API as the objects couldn't get created as of the validation errors...

### Expected Behavior

If the form check fails, no PN should be sent.

### Actual Behavior

The form fails and no object gets created. However, the PN gets sent via firebase anyways.

### Additional Information

`
Aug 17 16:14:10 DEBUG integreat_cms.cms.forms.push_notifications.push_notification_form - PushNotificationForm validated with cleaned data {'channel': 'news', 'mode': 'ONLY_AVAILABLE'}
Aug 17 16:14:10 DEBUG integreat_cms.cms.forms.push_notifications.push_notification_translation_form - PushNotificationTranslationForm submitted with errors: {'text': ['Ensure this value has at most 250 characters (it has 253).']}
`

![grafik](https://user-images.githubusercontent.com/15608678/185190848-29278997-dd7d-4155-a3eb-0f44db232501.png)

**Comment by timoludwig** [comment] 2022-08-17 16:27
Duplicate of #1631

**Closed** 2022-08-17 16:28 UTC
Labels: duplicate
