### ISSUE TITLE
LastUpdated timestamp should be renewed when content is still up to date

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1435] opened 2022-05-17 11:20 UTC
### Motivation
We want to improve quality of the content as well as improve trustworthiness of the information. Often information is too old or seems to be too old due to an old lastupdate-timestamp. We should motivate contributors to renew the time-stamp when the information is still valid.

### Proposed Solution
Contributors shall have the option to update the timestamp when the content is still valid. Also we could work within the analytics-page to show up the last x pages which are the oldest ones OR we show pages there which haven't been updated for x years.

**Comment by svenseeberg** [comment] 2022-05-17 11:22
Duplicate of #1258

**Closed** 2022-05-17 11:23 UTC
Labels: feature
