### ISSUE TITLE
Show diff to last version in side-by-side view

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-cms#1573] opened 2022-06-24 09:21 UTC
### Motivation

Integreat's content are updated over time and the translations need to follow. Sometimes there is a quite a lot of time between changes of the same page and the information on a page is quite long. 
It would be helpful for translators working directly in the system to get a view on the changes since the last translation was done. 

### Proposed Solution

Compare time stamp of last source language change and translation change and then show all changes in source language since that point in time? 

### Alternatives

Show the version history on the translation view and maybe highlight the time of the last change that was translated in the version history slider? 

### Additional Context

This is how it was done in WordPress. By clicking on "Show differences" in the translation view, the changes are shown in HTML-view.

![Integreat_WordPress_Screenshots from show differences since last translation_2](https://user-images.githubusercontent.com/16462172/175505217-16a38e3b-08f6-4fe8-8842-9ea5339fa325.jpg)
![Integreat_WordPress_Screenshots from show differences since last translation_1](https://user-images.githubusercontent.com/16462172/175505220-49954033-2e47-49fe-af6a-b9ce8d9f4151.jpg)

**Comment by FritjofK** [comment] 2022-06-24 09:22
Question came from pilot on Lesvos where they had translators working directly in the system. In Germany this (translators working within Integreat with the side-by-side view) happens very rarely, I think. 
In international context it might be used more often.

**Comment by timoludwig** [comment] 2022-08-14 09:49
Duplicate of #1449

**Closed by timoludwig** 2022-08-14 09:49 UTC
Labels: duplicate
