### ISSUE TITLE
Add links Integreat Wiki

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2661] opened 2024-02-15 14:55 UTC
### Motivation

It helps users if a link to Integreat Wiki is placed next to features/functionalities that often cause qurstions.

Links should directly go to the related part of Integreat Wiki, not the start page, to let users save effort.

TBD:
1. Which features and functionalities need help of Integreat Wiki (Service Team): candiates are Linkchecker, Translation, HIX.
2. How the links should look (icon?), where they should appear (UI/UX)

### Proposed Solution

Put more links to Integreat Wiki.

### Additional Context

We want to encourage users to visit Integreat Wiki to solve problems/questions by themselvs. (OKR)
We want to make Integreat System easier to use. (OKR)

**Comment by timobrembeck** [comment] 2024-02-27 19:59
As @JoeyStk [mentioned](https://github.com/digitalfabrik/integreat-cms/issues/2662#issuecomment-1963001428), this is a duplicate of #867.

**Closed by timobrembeck** 2024-02-27 19:59 UTC
Labels: feature, question, ui-ux
