### ISSUE TITLE
Issue with Cache in children endpoint

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1226] opened 2022-02-21 22:56 UTC
**This issue needs further investigation/testing**. For Malte the cache is currently disabled and the performance is acceptable. The priority of this issue depends on the performance of the migrated Integreat CMS.

### Describe the Bug
When calling random pages we sometimes get the following stack trace:
```
Feb 21 22:53:01 ERROR   django.request - Internal Server Error: /leakarlsruhefelsstrasse/de/wp-json/extensions/v3/children/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 178, in wrap
    return func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 124, in wrap
    return function(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 205, in children
    result.append(transform_page(public_translation))
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 22, in transform_page
    parent_page = page_translation.page.cached_parent
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/models/abstract_tree_node.py", line 210, in cached_parent
    return self.get_cached_ancestors()[-1]
IndexError: list index out of range
```
This trace persists until the cache is flushed.

### Steps to Reproduce

Happens randomly. Visit pages until it happens.

For the time being we could use a simple filter instead of a cache operation in https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/api/v3/pages.py#L231

**Comment by timoludwig** [comment] 2022-03-09 16:44
Unfortunately, this issue still persists when the cache is activated (or re-appeared in the latest version).

**Comment by melegiul** [comment] 2022-04-04 07:03
I could reproduce this locally, the problem is that moving a complete page tree changes its tree id, but the cache contains outdated tree ids for the page_translation - page relation.

Steps to reproduce:

1. Call the single page endpoint for a child page e.g. `curl -iL localhost:8008/augsburg/de/wp-json/extensions/v3/page?id=2` and watch close `page.tree_id` and `pagetranslation.page.tree_id` at this point, they are equal now: https://github.com/digitalfabrik/integreat-cms/blob/9d2ad577e55d3de58504d4f65cc80a24c8101df0/integreat_cms/api/v3/pages.py#L200
2. Now move the complete tree by moving its root page
3. Call the same endpoint of 1. again, now `page.tree_id` and `pagetranslation.page.tree_id` are unequal with `pagetranslation.page.tree_id` containing the outdated tree_id and the error above occurs.

Clearing the cache with `integreat-cms-cli invalidate cms` solves the problem

Suggested Changes:
Add manual cache invalidation after moving complete page trees.

**Closed** 2022-04-06 07:32 UTC
Labels: bug, question, prio: high
