### ISSUE TITLE
Expand all pages button

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1178] opened 2022-02-16 10:06 UTC
### Motivation
Some users don't know all the titles all the time. Therefore the search is sometimes not helping and users need to search it in the full tree manually.

### Proposed Solution
Add expand and collapse all buttons

**Comment by timoludwig** [comment] 2022-02-16 10:09
Duplicate of #1004

**Closed by timoludwig** 2022-02-16 10:09 UTC
Labels: feature
