### ISSUE TITLE
Add Google Translate as additional MT provider

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1436] opened 2022-05-17 11:26 UTC
### Motivation
Integreat and associated translations should take less time and process to maintain. Also it leads to lower costs of the whole project.

### Proposed Solution
We want to support additional automatic translation providers, for example Google and Microsoft. Each language should get an additional attribute that defines the preferred automatic translation provider.

The scope of this issue is to create additional issues that define the implementation steps.

### Alternatives
If TM-Connecting is too difficult at the start we could begin with the glossary (term database) and the enhance it with TM on a later date.

**Comment by timoludwig** [comment] 2022-05-17 11:29
Duplicate of #1104

**Comment by timoludwig** [comment] 2022-05-17 11:31
Ok sorry, didn't notice the Intento part... this isn't supported yet.

**Comment by dkehne** [comment] 2022-07-21 07:32
@ulliholtgrave @timoludwig prio high can be removed. don't focus that in the next 2 month...

**Comment by osmers** [comment] 2022-12-01 11:45
What I also take from the description and have not found in the open issues is that we want to connect our TM from MemoQ, do you want to open an extra issue for that?

**Comment by timoludwig** [comment] 2022-12-01 22:01
> What I also take from the description and have not found in the open issues is that we want to connect our TM from MemoQ, do you want to open an extra issue for that?

Indeed, could you open a separate issue for this? Ideally with a detailed description how you intend to use the TM.

**Comment by osmers** [comment] 2023-10-31 17:15
@dkehne Did we already decide to implement Google Translate or are we still in the process of deciding?
I think we can already create another issue regarding the "additional attribute that defines the preferred automatic translation provider", right?

**Comment by sarahsporck** [comment] 2023-11-07 14:41
As this ticket is not yet well defined this ticket will be moved into 24Q1 for now.

**Comment by dkehne** [comment] 2024-01-16 15:50
@MizukiTemma Google Translate Prio 1, Microsoft Translate Prio 2. Based on DeepL-quality-Report: https://www.deepl.com/en/quality.html

**Comment by dkehne** [comment] 2024-01-16 15:53
![information-14-00574-g003](https://github.com/digitalfabrik/integreat-cms/assets/4182469/ee7c08a1-40b8-406b-ab6d-b53cae87e10d)
Altough in general scorings Google seems to be a bit better.

**Comment by dkehne** [comment] 2024-02-06 19:15
It's really hard to tell at the moment if we go with the Cloud Translate API Basic (~costs around 20$/1m chars) or Cloud Translate API Advanced (~costs around 80$/1m chars). The advanced API can be trained with our data from the .tmx-Files.

Hopefully you can implement the API without forcing us to make this decision too early. I guess we need somehow both options to compare the results...So maybe go for the Basic-API first and then mabye add the API-Advanced as a second API in the test cms only?!

**Comment by MizukiTemma** [comment] 2024-02-07 12:24
> Hopefully you can implement the API without forcing us to make this decision too early. I guess we need somehow both options to compare the results...So maybe go for the Basic-API first and then mabye add the API-Advanced as a second API in the test cms only?!


The implementation was changed so both basic (v2) and advanced (v3) versions can be used, by specifying the variable `GOOGLE_TRANSLATE_VERSION`

**Closed** 2024-02-26 09:08 UTC
Labels: feature, prio: medium, effort: medium
