### ISSUE TITLE
Inform users about colliding permalinks

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1646] opened 2022-08-22 14:26 UTC
### Motivation
In https://admin.integreat-app.de/bochum/pages/de/1238/edit/ I try to change /informationen-zum-krieg-in-der-ukraine-2/ to /informationen-zum-krieg-in-der-ukraine/

It is not possible and always jumps back to /informationen-zum-krieg-in-der-ukraine-2/ even i have renamed the other page which was orginally named /informationen-zum-krieg-in-der-ukraine/

### Proposed Solution
Show a message after saving the page that the proposed slug is already in use. State which page and version are responsible and link to the colliding page translation history.

### Alternatives
Only link to the page instead of the history.

### Additional Context
If users have problems after the change, we could discuss implementing a "slug history clean up button".

Internal discussion: https://chat.tuerantuer.org/digitalfabrik/threads/97zc3mwac7yi9jk3emrr5ec4oc

**Comment by timoludwig** [comment] 2022-08-22 15:29
This is the expected behavior of a _permalink_. The old link continues to direct to the old page (and this "blocks" the link for other pages), even after the link is changed.
If you don't want this behavior, we can change it, but still this would be a feature request and no bug. Keep in mind that this would imply that all of the old links won't continue to work when you edit them. 
Please discuss this in the service team if you are really sure.

**Comment by svenseeberg** [comment] 2022-08-27 09:03
I don't think that a permalink should be changeable. It would not be a permalink anymore.

**Comment by svenseeberg** [comment] 2022-08-27 09:05
And to answer Daniel's question: you can change the link when the old page is being removed and the permalink is "free" again.

**Comment by timoludwig** [comment] 2022-08-27 09:35
Another possibility would be to keep the permalink behavior as it is, but in the page form next to the link we provide a button "delete permalink history" to free a specific link for other pages without deleting the whole page...
Not sure though if this creates more problems than it solves... but maybe for expert users or staff members it might be helpful?

**Comment by dkehne** [comment] 2022-08-27 09:49
We will discuss in on Monday in our serviceteam call. 
After duplicating the deutschlandvorlage or another city, permalink changes are necessary.

**Comment by dkehne** [comment] 2022-08-27 09:50
Due to the fact that i cannot reopen issues here, i would create a new one if we come to conclusion that it is necessary

**Comment by timoludwig** [comment] 2022-08-27 11:40
> Due to the fact that i cannot reopen issues here, i would create a new one if we come to conclusion that it is necessary

Deliberately creating duplicate issues is always a bad idea. Please just leave a comment with your conclusion and we can reopen the ticket.
However, I also invited you to the digitalfabrik orga, this hopefully gives you permission to reopen issues.

**Comment by svenseeberg** [comment] 2022-08-27 12:02
It is possible to change perma links. But you're not allowed to use already used permalinks.

Also there is the option that we do change permalinks in the database as application admins.

**Comment by dkehne** [comment] 2022-08-29 08:46
Service team answer: Removing the "unprofessional characters" from the permalinks is more important than the permalink history. Question in that case: Can we remove the permalink history our does that also affect internal links in cases of permalink-changes?

**Comment by svenseeberg** [comment] 2022-08-29 18:05
1) You can change the permalink to anything that does not collide with existing permalinks. For example you could simply change the slug to `informationen-krieg-in-der-ukraine` or `information-zum-krieg-in-der-ukraine` which does not really take anything away from from the readability. This just needs a little creativity instead of just removing the last characters.
2) You can simply delete the page that causes the collision. This will allow you to re-use the slug.

**Comment by dkehne** [comment] 2022-08-29 20:32
The permalink history is the problem here in combination with the fact that the uniquess is now defined by only one part of the slug (not the whole slug as it was before). WordPress was completly fine. The requirements haven't changed. It wasn't improved with Django, it's now worse. 

"Collide with existing links" is problematic because an existing link is everything what has existed in past at single pages that are not deleted.

From the experience of the first 3 month it is not intuitive to our users. Some cities asked us how to change it but it was even to complex to explain for us (although we don't want to explain at all)

**Comment by dkehne** [comment] 2022-08-29 20:34
"To improve the functionality, we could add a message that explains which page has a colliding slug and maybe even link to it." would be a good idea if the permalink history can also be looked up or is explained somewhere. We have dropped of the trainings for the system because the plan of the migration was that it all becomes easier and more self-explaining.

**Comment by svenseeberg** [comment] 2022-08-30 06:32
I do think there are some misconceptions about the idea behind the permalinks. The cause for creating permalinks is that they do not change, because websites etc link to the pages. Humans are usually bad with maintaining these links over a long time. Breaking links are bad for at least 2 reasons: a) It impacts search engine scores because they at least somewhat depend on the number of links to a page. b) Users cannot follow links.

Now in our case there are quite often huge changes in structure and therefore changes in the page path. This ensures that links still work after changing the structure. The rest is only for readability

I'm also not convinced that the trailing number is actually a problem. There are tons of pages that by default without collisions add some non-readable parts to the end of the path, for example heise.de or theregister.co.uk. Also, the Google link guide is also totally aligned with this behavior (https://developers.google.com/search/docs/advanced/guidelines/url-structure).

**Comment by svenseeberg** [comment] 2022-08-30 07:09
> would be a good idea if the permalink history can also be looked up or is explained somewhere. We have dropped of the trainings for the system because the plan of the migration was that it all becomes easier and more self-explaining.

Well, IMHO it is. The permalinks work quite well. The system will automatically correct them if they're already used.

**Comment by timoludwig** [comment] 2022-11-04 15:06
After changing the scope of the issue (only inform about colliding permalinks instead of allowing the user to change them), this is now a duplicate of #1521.

**Closed by timoludwig** 2022-11-04 15:06 UTC
Labels: feature, prio: high, effort: low
